### ISSUE TITLE
readme.md

### ISSUE THREAD

**Issue by HienThuThiDai** [MicrosoftLearning/mslearn-dp100.zh-tw#1]
English:
How should I use these files relative to the released MOC files?

Current Translation:
我該如何使用與相對於已釋放的 MOC 檔案之這些檔案？

Suggested Translation:
相對於發佈的 MOC 檔案，我應該如何使用這些檔案？

Description:
Mistranslation

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
https://dev.azure.com/ceapex/CEINTL/_workitems/edit/688120

**Comment by stonezy123** [comment]
Run bugfix tool and waiting for result.

**Comment by stonezy123** [comment]
![image](https://user-images.githubusercontent.com/49666210/186311432-10b16d8e-da9a-4847-9ba2-13e43db71662.png)
